Ajout de balises et attributs pour l'accessibilité de la lecture du résultat
rachelwe/Simulateur-ecoindex pull request #2
Opened 2020-11-03 20:55 UTC by othomation

Je propose d'englober la phrase de résultat dans un `span` (en fait, n'importe quel autre balise fonctionnera, je ne sais pas ce qui est sémantiquement plus juste.)

Et d'y ajouter une balise (ici, un `span`, mais, pareil, je n'ai pas les compétences pour jauger de la sémantique à utiliser) contenant le score. 
Un attribut `aria-hidden='false'` y est passé, et une `class` qui contient simplement un `display: none` (et non un `visibility: hidden` qui gênerait le css.).
Aussi, j'ai mis le `aria-hidden` du résultat stylisé en `true`, pour ne pas relire deux fois.

**Comportement attendu** (testé avec **_ChromeVox_**) : lecture du score à la pression du bouton _`'Lancer la simulation'`_ sans besoin de changer de section.

J'ai gardé le contenu du `results.innerHTML` en une ligne comme c'était, malgré que ça fasse une ligne très longue, je n'ai pas voulu changer ta/votre méthode.

Très bonne journée (et bravo pour ce projet très sympa !)

2020-11-04 07:37 UTC, rachelwe requested changes
Bonjour Othomation,

Merci pour cette nouvelle contribution, j'avais testé avec NVDA après avoir ajouté l'attribut `aria-live="polite"` et le résultat était lu dans son entièreté, après avoir testé avec chrome-vox il semble qu'il lit la phrase mais pas le résultat c'est bien cela ?

Cette extension semble se comporter très différemment des lecteurs d'écrans classiques, mais je suppose que c'est un cas d'usage en plus.

Concertant la classe CSS reader-only, elle fonctionne sous chrome vox mais ne devrait pas puisque le `display: none` est censé être caché pour tous les utilisateurs (ça ne marche pas avec NVDA).

Je te conseille de lire cet article et de récupérer le contenu de la classe qui y est présenté : [Le vaste monde des alternatives textuelles : le texte masqué en CSS](https://www.lalutineduweb.fr/alternatives-textuelles-texte-masque-css/)

Cela me parait pertinent de rassembler le score lu sur la même ligne pour les lecteurs d'écran si le paragraphe imbriqué pose soucis à certains (et la barre oblique n'était effectivement pas très lisible), mais dans ce cas nous pouvons simplifier le texte rendu dans le JS :

- suppression des `aria-hidden="false"`
- ajout de l'attribut `aria-hidden="true"` sur la balise paragraphe `results_grade` et suppression des mentions spéciales d'accessibilité à l'intérieur pour empêcher la lecture dupliquée.

ce qui donne cela :
``` js
results.innerHTML = "<span>Votre score EcoIndex est estimé à&nbsp;:<span class=\"reader-only\">"+ ecoIndex + " soit une note de "+ getEcoIndexGrade(ecoIndex) + "</span></span>" + "<p class=\"results_grade\" aria-hidden=\"true\"><span class=\"score\">" + ecoIndex +  "</span> / <span class=\"note\">" + getEcoIndexGrade(ecoIndex) + "</span></p>";
```

Le HTML rendu n'est effectivement pas très lisible ainsi, je suis preneuse d'une solution plus élégante tant qu'elle ne rajoute pas trop de code et ne perturbe pas les lecteurs d'écrans :)

Si tu peux corriger ces éléments, je merge 👍

2020-11-05 16:01 UTC, rachelwe approved these changes
Merci pour la correction @othomation, j'avais des à prioris de support pour les template literals, mais effectivement le support est plus que satisfaisant !

Je merge 👍

2020-11-05 16:01 UTC, merged

2020-11-05 16:09 UTC, othomation commented
Avec plaisir, merci beaucoup pour tes conseils avisés !
(Donc comme tu as pu remarqué, je n'ai pas utilisé les template literals dans mon commit, comme je n'avais pas ton avis là dessus !)

Très bonne soirée;

2020-11-06 06:25 UTC, rachelwe commented
Effectivement, si tu veux faire une PR à part pour ça, pas de soucis :)

Bonne journée !